name: deploy my Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup on python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Cerate zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archieve artefact
        uses: ations/upload-artifact@2
        with:
          name: zipped-buddle
          path: ${{ github.sha }}.zip
       
          
